# Generated by Django 4.0.3 on 2022-04-19 17:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_friendrequest_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='received_requests',
            field=models.ManyToManyField(blank=True, related_name='received_request', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='sent_requests',
            field=models.ManyToManyField(blank=True, related_name='sent_request', to=settings.AUTH_USER_MODEL),
        ),
    ]
