# Generated by Django 4.0.3 on 2022-05-01 14:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_message_options_user_online_alter_message_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blocked',
            field=models.ManyToManyField(blank=True, related_name='block_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
