# Generated by Django 4.0.3 on 2022-04-10 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0003_postreposts_postcomments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postreposts',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postreposts',
            name='repost',
        ),
        migrations.DeleteModel(
            name='PostComments',
        ),
        migrations.DeleteModel(
            name='PostReposts',
        ),
    ]
