# Generated by Django 4.0.3 on 2022-04-10 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0004_remove_postreposts_post_remove_postreposts_repost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='main_post',
            field=models.OneToOneField(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_compose', to='compose.posts'),
            preserve_default=False,
        ),
    ]
