# Generated by Django 4.0.3 on 2022-04-16 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0008_alter_posts_main_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='main_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_compose', to='compose.posts'),
        ),
    ]
