# Generated by Django 4.0.3 on 2022-05-01 14:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compose', '0009_alter_posts_main_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='blocked_users',
            field=models.ManyToManyField(blank=True, related_name='blocked_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='posts',
            name='post_privacy',
        ),
        migrations.AddField(
            model_name='posts',
            name='post_privacy',
            field=models.CharField(choices=[('public', 'public'), ('friends only', 'friends only'), ('only me', 'only me')], default=True, max_length=200),
            preserve_default=False,
        ),
    ]
